config/routes.rb
Pilotcar::Application.routes.draw do


  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :bids
  resources :pins

  resources :listings do
    collection do
      get 'search'
    end
    resources :notifications
    resources :pins
  end

  resources :notifications
  resources :pins

  resources :categories do
    resources :subcategories do
      resources :listings
    end
  end

  resources :loads do
    resources :bids
  end

  devise_for :truckers
  devise_for :pilots #, controllers: { registrations: "pilots/registrations", sessions: "pilots/sessions" }

  # Static
  root "pages#home"
  get "testhome" => "pages#home2"
  get "contact" => "pages#contact"
  get "about" => "pages#about"
  get "signup" => "pages#signup"
  get "privacystatement" => "pages#privacy"

  #custom routes
  get "/loads/:id/clone"	=> "loads#clone"
  get "clone" => "loads#clone"
  match '/mylistings', to: 'listings#mylistings', via: :get
  match '/adminlistings', to: 'listings#adminlistings', via: :get
  match '/subcategories/find_by_category', to: 'subcategories#find_by_category', via: :post
  get "/states" => "categories#index"

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

end

app/models/load.rb
class Load < ActiveRecord::Base
    belongs_to :trucker 
    has_many :bids
    has_many :pilots, through: :bids
    
    validates :pickup_datetime,
              date: { after: Proc.new { 1.day.ago }, message: 'must be after current date/time'}  
                      
    validates :delivery_datetime,
              date: { after: :pickup_datetime, message: 'must be after pick up date/time' } 
              
    validates_format_of :origin_zipcode, :with => /^\d{5}(-\d{4})?$/, :multiline => true,
                        :message => "should be in the form 12345 or 12345-1234"          
              
    validates_format_of :destination_zipcode, :with => /^\d{5}(-\d{4})?$/, :multiline => true,
                        :message => "should be in the form 12345 or 12345-1234"                                              
end

app/controllers/admin/loads_controller.rb
module Admin
  class LoadsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Load.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Load.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController
  before_action :set_load, only: [:show, :edit, :update, :destroy, :clone]
  # before_action :authenticate_trucker!
  before_action :correct_trucker, only: [:edit, :update, :destroy, :clone]

  def index
    @loads = Load.all
  end

  def show
  end

  def new
    @load = current_trucker.loads.build
  end

  def edit
  end

  def create
    @load = current_trucker.loads.build(load_params)
      if @load.save
        redirect_to @load, notice: 'Load was successfully created.'
      else
        render action: 'new'
      end
  end

  def update
      if @load.update(load_params)
        redirect_to @load, notice: 'Load was successfully updated.'
      else
        render action: 'edit'
      end
  end

  def destroy
    @load.destroy
      redirect_to loads_url
  end
  
  def clone
      @load = Load.find(params[:id]) # find original object
      @load = Load.new(@load.attributes) # initialize duplicate (not saved)
      render :new # render same view as "new", but with @load attributes already filled in
  end
    


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_load
      @load = Load.find(params[:id])
    end

    def correct_trucker
      @load = current_trucker.loads.find_by(id: params[:id])
      redirect_to loads_path, notice: "Not authorized to edit this load request" if @load.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def load_params
      params.require(:load).permit(:origin_country, :origin_city, :origin_state, :origin_zipcode, 
      :destination_country, :destination_city, :destination_state, :destination_zipcode, :fee, 
      :fee_type, :distance, :pickup_datetime, :delivery_datetime, :special_notes, :pilotcar_count, 
      :polecar_needed, :current_status)
    end
end

app/helpers/loads_helper.rb
module LoadsHelper
  
  def us_states
      [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
      ]
  end 
end

app/views/loads/_form.html.erb
<%= form_for(@load) do |f| %>
  <% if @load.errors.any? %>
    <div class="alert alert-danger" role="alert">
		<h4><%= pluralize(@load.errors.count, "error") %> prohibited this load from being saved:</h4>
      <ul>
      <% @load.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <H3> <label for="Starting Point Info">Starting Point Info</label></H3><br>
  <div class="form-group">
    <label for="City">City</label><br>
    <%= f.text_field :origin_city, class: "form-control", placeholder: 'Starting Point City', required: true %>
  </div>
  <div class="form-group">
    <label for="State">State</label><br>
	<%= f.select :origin_state, options_for_select(us_states, :selected => @load.origin_state), required: true %> 
	<!-- <%= f.select :origin_state, options_for_select(us_states), required: true %> -->
  </div>
  <div class="form-group">
    <label for="ZipCode">ZipCode</label>
	<table> <tr>
		<td><%= f.text_field :origin_zipcode, class: "form-control", placeholder: 'Starting Point Zipcode', required: true %></td>
		<td> &nbsp &nbsp </td> 
		<td><div class="actions">
			<%= link_to 'http://www.geonames.org/postalcode-search.html?q=&country=us', :target => '_blank' do %>
			<span class="glyphicon glyphicon-eye-open"></span> (LookUp Zip)
			<% end %>
			</div>
		</td>
	</tr> </table>		
  </div>
  <h3><label for="Destination">Destination</label></h3><br>
  <div class="form-group">
    <label for="City">City</label><br>
    <%= f.text_field :destination_city, class: "form-control", placeholder: 'Destination City', required: true %>
  </div>
  <div class="form-group">
    <label for="State">State</label><br>
    <%= f.select :destination_state, options_for_select(us_states, :selected => @load.destination_state), required: true %>
  </div>
  <div class="form-group">
    <label for="ZipCode">ZipCode</label>
	<table> <tr>
		<td><%= f.text_field :destination_zipcode, class: "form-control", placeholder: 'End Point Zipcode', required: true %></td>
		<td> &nbsp &nbsp </td> 
		<td><div class="actions">
			<%= link_to 'http://www.geonames.org/postalcode-search.html?q=&country=us', :target => '_blank' do %>
			<span class="glyphicon glyphicon-eye-open"></span> (LookUp Zip)
			<% end %>
			</div>
		</td>
	</tr> </table>		
  </div>
  <h3><label for="Load Details">Load Details</label></h3><br>  
	<div class="form-group">
    <%= f.label "Anticipated Rate" %> 
	<%= number_to_currency(f.number_field :fee, class: "form-control", :step =>0.01, min: 0, placeholder: 'USD $0.00', required: true) %>
	</div>
    <div class="form-group">
    <%= f.radio_button :fee_type, "per mile", label: "per mile" %> per mile &nbsp
    <%= f.radio_button :fee_type, "for trip", label: "for trip" %> for trip
  </div>
  <div class="form-group">
    <label for="Distance">Distance</label>
	<table> <tr>
		<td><%= f.text_field :distance, class: "form-control", min: 0, placeholder: 'Approximate US miles', required: true %></td>
		<td> &nbsp &nbsp </td> 
		<td><div class="actions">
			<%= link_to 'http://www.zip-codes.com/distance_calculator.asp', :target => '_blank' do %>
			<span class="glyphicon glyphicon-eye-open"></span> (LookUp Distance)
			<% end %>
			</div>
		</td>
	</tr> </table>		
  </div>
  <div class="form-group">
    <%= f.label "Load (Date / Time)" %><br>
    <%= f.datetime_select :pickup_datetime, :class => 'datepicker', :minute_step => 15 %>
  </div>
  <div class="form-group">
    <%= f.label "Drop (Date / Time)" %><br>
    <%= f.datetime_select :delivery_datetime, class: "form-control", :minute_step => 15 %>
  </div>
  <div class="form-group">
    <%= f.label :special_notes %><br>
    <%= f.text_area :special_notes, class: "form-control" %>
  </div>
  
  <div class="form-group">
	<%= f.label "Specify number of pilot cars required: " %> &nbsp
    <%= f.radio_button :pilotcar_count, 1, label: "1", checked: true %> 1 &nbsp
    <%= f.radio_button :pilotcar_count, 2, label: "2" %> 2 &nbsp
    <%= f.radio_button :pilotcar_count, 3, label: "3" %> 3 &nbsp
	<%= f.radio_button :pilotcar_count, 4, label: "4" %> 4 
  </div> 
 
  <div class="form-group">
	<%= f.check_box :polecar_needed %> &nbsp
	<%= label_tag(:polecar_needed, "Pole Car Required") %>
  </div>
 <% if @load.id? %>
  <div class="form-group">
	<%= f.label "Current Status" %> &nbsp
	<%= f.select(:current_status, options_for_select([['ACTIVE', 'ACTIVE'], 
	['ON HOLD', 'ON HOLD'], ['COVERED', 'COVERED']]), {}, {class: "form-control"}) %>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</form>

app/views/loads/_gploadlist.html.erb
<div class="container">
	<h3>New Pilot Car Requests</h3>
	<div class="table-responsive">
		<table class= 'table table-condensed' id= 'loads'>
		  <thead> 	 	<!-- table header  -->
		    <tr>
		      <th>Pick Up</th>
		      <th>State</th>
		      <th>Destination</th>
		      <th>State</th>
		      <th>Est. Rate</th>
			  <th>Rate Type</th>
		      <th>Distance</th>
		      <th>Load (Date/Time)</th>
		      <th>Drop (Date/Time)</th>
		      <th>Pilotcars</th>
		      <th>Polecar</th>
		    </tr>
		  </thead> 		 <!-- Second row header end  -->
		  <tbody>		  	
		    	<tr>
			    	<% @loads.each do |load| %>
					<% if load.current_status == "ACTIVE" and load.pickup_datetime > Date.today %> 
		  					        <td><%= load.origin_city %></td>
		  					        <td><%= load.origin_state %></td>
		  					        <td><%= load.destination_city %></td>
		  					        <td><%= load.destination_state %></td>
		  					        <td><%= number_to_currency(load.fee) %> </td>
		  							<td><%= load.fee_type %> </td>
		  					        <td><%= load.distance %></td>
		  					        <td><%= I18n.l load.pickup_datetime, format: :myformat %></td>
		  							<td><%= I18n.l load.delivery_datetime, format: :myformat %></td>
		  					        <td align="center"><%= load.pilotcar_count %></td>
		  					        <td align="center"><% if load.polecar_needed %>
		  								Yes 
		  								<% else %>
		  								No 
		  								<% end %>
		  							</td>
						
		      </tr>
			  		<% end %>
			  		<% end %>
				</tbody>
			</table>
		</div>
			<br>				
</div>

app/views/loads/_ploadlist.html.erb
<% if pilot_signed_in? %>
<div class="container">
	<h3>Current Pilot Car Requests</h3>
	<div class="table-responsive">
		<table class= 'table table-condensed' id= 'loads'>
		  <thead> 	 	<!-- table header  -->
		    <tr>
		      <th>Pick Up</th>
		      <th>State</th>
		      <th>Destination</th>
		      <th>State</th>
		      <th>Est. Rate</th>
			  <th>Rate Type</th>
		      <th>Distance</th>
		      <th>Load (Date/Time)</th>
		      <th>Drop (Date/Time)</th>
		      <th>Pilotcars</th>
		      <th>Polecar</th>
		    </tr>
		  </thead> 		 <!-- Second row header end  -->
		  <tbody>		  	
		    	<tr>
					<div class="editlink">
			    	<% @loads.each do |load| %>
					<% if load.current_status == "ACTIVE" and load.pickup_datetime > Date.today %>
		  					        <td><%= link_to load.origin_city, load %></td>
		  					        <td><%= link_to load.origin_state, load %></td>
		  					        <td><%= link_to load.destination_city, load %></td>
		  					        <td><%= link_to load.destination_state, load %></td>
		  					        <td><%= link_to number_to_currency(load.fee), load %> </td>
		  							<td><%= link_to load.fee_type, load %> </td>
		  					        <td><%= link_to load.distance, load %></td>
		  					        <td><%= I18n.l load.pickup_datetime, format: :myformat %></td>
		  							<td><%= I18n.l load.delivery_datetime, format: :myformat %></td>
		  					        <td align="center"><%= load.pilotcar_count %></td>
		  					        <td align="center"><% if load.polecar_needed %>
		  								Yes 
		  								<% else %>
		  								No 
		  								<% end %>
		  							</td>
								</div>
		  			      </tr>
					<% end %>
					<% end %>
					<% end %>
				</tbody>
			</table>
			<br>	
		</div>
</div>		

app/views/loads/_tloadlist.html.erb
<% if trucker_signed_in? %>
<div class="container">
	<h3>Active Pilot Car Requests</h3>
<div class="table-responsive">
		<table class= 'table table-condensed' id= 'pilot'>
		  <thead> 	 	<!-- table header  -->
		    <tr>
		      <th>Pick Up</th>
		      <th>State</th>
		      <th>Destination</th>
		      <th>State</th>
		      <th>Est. Rate</th>
			  <th>Rate Type</th>
		      <th>Distance</th>
		      <th>Load (Date/Time)</th>
		      <th>Drop (Date/Time)</th>
		      <th>Pilotcars</th>
		      <th>Polecar</th>
		    </tr>
		  </thead> 		 <!-- Second row header end  -->
		  <tbody>		  	
		    	<tr>
			    	<% @loads.each do |load| %>
					<% if load.trucker == current_trucker and load.current_status == "ACTIVE" and load.pickup_datetime > Date.today %> 
		  					        <td><%= link_to load.origin_city, load %></td>
		  					        <td><%= link_to load.origin_state, load %></td>
		  					        <td><%= link_to load.destination_city, load %></td>
		  					        <td><%= link_to load.destination_state, load %></td>
		  					        <td><%= link_to number_to_currency(load.fee), load %> </td>
		  							<td><%= link_to load.fee_type, load %> </td>
		  					        <td><%= link_to load.distance, load %></td>
		  					        <td><%= I18n.l load.pickup_datetime, format: :myformat %></td>
		  							<td><%= I18n.l load.delivery_datetime, format: :myformat %></td>
		  					        <td align="center"><%= load.pilotcar_count %></td>
		  					        <td><% if load.polecar_needed %>
		  								Yes 
		  								<% else %>
		  								No 
		  								<% end %>
		  							</td>
		  			      </tr>
					<% end %> <% end %> <% end %>
				</tbody>
			</table>
					<%= link_to 'Create a New Pilot Car Request', new_load_path, 
					class: "btn btn-primary" %>
			<br>
			<br>
			</div>
</div>
<div class="container">
	<h3>Covered Pilot Car Requests</h3>
<div class="table-responsive">
		<table class= 'table table-condensed' id= 'covered'>
		  <thead> 	 	<!-- table header  -->
		    <tr>
		      <th>Pick Up</th>
		      <th>State</th>
		      <th>Destination</th>
		      <th>State</th>
		      <th>Est. Rate</th>
			  <th>Rate Type</th>
		      <th>Distance</th>
		      <th>Load (Date/Time)</th>
		      <th>Drop (Date/Time)</th>
		      <th>Pilotcars</th>
		      <th>Polecar</th>
		    </tr>
		  </thead> 		 <!-- Second row header end  -->
		  <tbody>		  	
		    	<tr>
			    	<% @loads.each do |load| %>
					<% if load.trucker == current_trucker and load.current_status == "COVERED" and load.pickup_datetime > Date.today %> 
		  					        <td><%= link_to load.origin_city, load %></td>
		  					        <td><%= link_to load.origin_state, load %></td>
		  					        <td><%= link_to load.destination_city, load %></td>
		  					        <td><%= link_to load.destination_state, load %></td>
		  					        <td><%= link_to number_to_currency(load.fee), load %> </td>
		  							<td><%= link_to load.fee_type, load %> </td>
		  					        <td><%= link_to load.distance, load %></td>
		  					        <td><%= I18n.l load.pickup_datetime, format: :myformat %></td>
		  							<td><%= I18n.l load.delivery_datetime, format: :myformat %></td>
		  					        <td align="center"><%= load.pilotcar_count %></td>
		  					        <td><% if load.polecar_needed %>
		  								Yes 
		  								<% else %>
		  								No 
		  								<% end %>
		  							</td>
		  			      </tr>
					<% end %> <% end %>
				</tbody>
			</table>
			<br>
			<br>
			</div>
</div>
<div class="container">
	<h3>Past Pilot Car Requests</h3>
<div class="table-responsive">
		<table class= 'table table-condensed' id= 'archived'>
		  <thead> 	 	<!-- table header  -->
		    <tr>
		      <th>Pick Up</th>
		      <th>State</th>
		      <th>Destination</th>
		      <th>State</th>
		      <th>Est. Rate</th>
			  <th>Rate Type</th>
		      <th>Distance</th>
		      <th>Load (Date/Time)</th>
		      <th>Drop (Date/Time)</th>
		      <th>Pilotcars</th>
		      <th>Polecar</th>
			  <th>Status</th>
		    </tr>
		  </thead> 		 <!-- Second row header end  -->
		  <tbody>		  	
		    	<tr>
			    	<% @loads.each do |load| %>
					<% if load.trucker == current_trucker and (load.pickup_datetime <= Date.today or load.current_status == "ON HOLD")  %> 
		  					        <td><%= link_to load.origin_city, load %></td>
		  					        <td><%= link_to load.origin_state, load %></td>
		  					        <td><%= link_to load.destination_city, load %></td>
		  					        <td><%= link_to load.destination_state, load %></td>
		  					        <td><%= link_to number_to_currency(load.fee), load %> </td>
		  							<td><%= link_to load.fee_type, load %> </td>
		  					        <td><%= link_to load.distance, load %></td>
		  					        <td><%= I18n.l load.pickup_datetime, format: :myformat %></td>
		  							<td><%= I18n.l load.delivery_datetime, format: :myformat %></td>
		  					        <td align="center"><%= load.pilotcar_count %></td>
		  					        <td align="center"><% if load.polecar_needed %>
		  								Yes 
		  								<% else %>
		  								No 
		  								<% end %>
		  							</td>
									<% if load.pickup_datetime <= Date.today %>
									<td>EXPIRED</td>
									<% else %>
									<td><%= load.current_status %></td>
									<% end %>
		  			      </tr>
					<% end %> 
					<% end %>
				</tbody>
			</table>	
			</div>
</div>  

app/views/loads/clone.html.erb
<div class="container">
<h3>Edit Pilot Car Request</h3>

<%= render 'form' %>

<%= link_to 'Show', @load %> |
<%= link_to 'Back', loads_path %>
</div>

app/views/loads/edit.html.erb
<% if @load.trucker == current_trucker and @load.current_status == "ACTIVE" and @load.pickup_datetime > (Date.today - 1.day) %>
<div class= "container">
<div class='jumbotron'>
<h3>Edit Pilot Car Request</h3>

<%= render 'form' %>

<%= link_to 'Show', @load %> |
<%= link_to 'Back', loads_path %>
</div>
<% else %>
<div class="jumbotron">
<p class="bg-danger">You can not edit this record.</p>
</div>
</div>
<% end %>

app/views/loads/index.html.erb
	<div class="container">
	<div class="jumbotron">
		<h4>Welcome to Pilot Car Finder</h4>
		<p><%= link_to "Sign up today FREE", signup_path, class: "btn btn-primary" %></p>
	</div>
     <% if trucker_signed_in? %> 
	 <%= render 'tloadlist' %> <!-- render truckers load list -->
     <% else %>
     <% if pilot_signed_in? %>
	 <%= render 'ploadlist' %>	  <!-- render pilotcar load list -->
     <% else %>
	<%= render 'gploadlist' %> <!-- render general public load list -->
 <% end %>  
 <% end %>  
</div>
 <br>

app/views/loads/new.html.erb
<div class= "container">
<div class='jumbotron'>
<h3>Pilot Car Request</h3>

<%= render 'form' %>

<%= link_to 'Back', loads_path %>
<br><br>
</div>
</div>

app/views/loads/show.html.erb
<div class="container">
	<div class="jumbotron">
		 <h3>Pilot Car Request Summary</h3>
		<p>
		  <h3>Origin</h3>
		  <%= @load.origin_city %> , &nbsp  <%= @load.origin_state %> &nbsp <%= @load.origin_zipcode %> &nbsp <%= @load.origin_country %><br>
		  Load (Date / Time): <%= I18n.l @load.pickup_datetime, format: :myformat %><br><br>
		  <strong>Pilotcar count:</strong>
		  <%= @load.pilotcar_count %><br>
		  <strong>Polecar Required:</strong>
		  <% if @load.polecar_needed %>
		  Yes
		  <% else %>
		  No
		  <% end %>
		</p>  
  
		<p>
		  <h3>Destination</h3>
		   <%= @load.destination_city %> , &nbsp  <%= @load.destination_state %> &nbsp <%= @load.destination_zipcode %> &nbsp <%= @load.destination_country %><br>
		   Drop (Date / Time):<%= I18n.l @load.delivery_datetime, format: :myformat %>
		</p>

		<p>
		  <h3>Additional Details:</h3>

		  <strong>Expected Fee:</strong>
		  <%= number_to_currency(@load.fee) %> &nbsp <%= @load.fee_type %><br>
		  <strong>Approximate Distance:</strong>
		  <%= @load.distance %> &nbsp miles<br>
		  <strong>Additional Notes:</strong><br>
		  <%= @load.special_notes %><br>
		  <strong>Current status:</strong>
		  <%= @load.current_status %><br>
		</p>
				<% if pilot_signed_in? %>
				<%= link_to 'New Bid', new_load_bid_path(@load), class:"btn btn-primary" %>
				<% end %>
		<table>
			<tr>
				<% if @load.trucker == current_trucker and @load.current_status == "ACTIVE" and @load.pickup_datetime > Date.today %>
				<td><%= link_to 'Edit', edit_load_path(@load), class: "btn btn-primary" %> &nbsp </td>
				<td><%= link_to 'Change Status', edit_load_path(@load), class: "btn btn-primary" %> &nbsp </td>
				<% end %>
				<td>
				<% if @load.trucker == current_trucker %>
				<%= link_to 'Duplicate Run', action: 'clone', id: @load.id, class:"btn btn-default" %>  &nbsp 
				</td>
			</tr>
		</table><br>
				<td><%= link_to 'Back to List', loads_path, class:"btn btn-default" %> &nbsp </td>
				<% end %>

		<br><br>
	</div>
</div>