config/routes.rb
Pilotcar::Application.routes.draw do


  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :bids
  resources :pins

  resources :listings do
    collection do
      get 'search'
    end
    resources :notifications
    resources :pins
  end

  resources :notifications
  resources :pins

  resources :categories do
    resources :subcategories do
      resources :listings
    end
  end

  resources :loads do
    resources :bids
  end

  devise_for :truckers
  devise_for :pilots #, controllers: { registrations: "pilots/registrations", sessions: "pilots/sessions" }

  # Static
  root "pages#home"
  get "testhome" => "pages#home2"
  get "contact" => "pages#contact"
  get "about" => "pages#about"
  get "signup" => "pages#signup"
  get "privacystatement" => "pages#privacy"

  #custom routes
  get "/loads/:id/clone"	=> "loads#clone"
  get "clone" => "loads#clone"
  match '/mylistings', to: 'listings#mylistings', via: :get
  match '/adminlistings', to: 'listings#adminlistings', via: :get
  match '/subcategories/find_by_category', to: 'subcategories#find_by_category', via: :post
  get "/states" => "categories#index"

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :listings
  has_many :subcategories
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Category.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Category.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :set_category, only: :show

  def index
    @categories = Category.all.order(:name)
  end

  def show
    @listings = @category.listings.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    @subcategories = @category.subcategories
  end

  private

    def set_category
     @category = Category.find(params[:id])
    end

end

app/views/categories/index.html.erb
<% title 'Pilot Car Companies and Oversized Load Escorts USA List' %>
<% description 'State by State list of Pilot car operators and oversized load escorts in the USA. The best Pilot Car Companies Directory ever.' %>
<% keywords 'pilot car companies, pilotcars, oversized load escorts' %>
<%= render 'layouts/search' %>
<div class='container'>
	<div class="well well-sm">
		<h5>USA ></h5>
		<h3>Pilot Car USA Directory</h3>
		<div class="container-fluid">
			<div class="row">
				<big>
					<% @categories.each do |category| %>
						<div class="col-md-2 col-sm-3 col-xs-5"><%= link_to category.name, category_path(category) %></div>
					<% end %>
				</big>
			</div>
		</div>
	</div>
</div>
<%= render 'layouts/tripleboxes' %>

app/views/categories/show.html.erb
<% title @category.name + ' Pilot Car Directory'  %>
<% description @category.name + ' pilot car companies and oversized load escorts. Most complete pilot car directory in ' + @category.name %>
<% keywords @category.name + ', pilotcars, oversize load escorts' %>
<%= render 'layouts/search' %>
<div class='container'>
	<div class="well well-sm">
		<h5><%= link_to 'USA', states_path %> > <%= @category.name %>  > Metro Area List</h5>
	<h3><%= @category.name %> Pilot Car Directory</h3>
	<div class="container-fluid">
		<div class="row"><p><big>
			  <%  @subcategories.each do |subcategory| %>
			    <div class="col-md-2 col-sm-3 col-xs-5"><%= link_to subcategory.name, category_subcategory_path(@category, subcategory)  %></div>
				<% end %>
			</div></big></p>
			</div>
<hr>
<div class="container">
		  <div class="row">
				  <div class="col-xs-12 col-sm-7 col-md-7">
					  <% if @listings.present? %>	
					  <%  @listings.each do |listing| %>
						<h4><%= link_to listing.title, listing_path(listing.slug) %></h4>
						<b><%= listing.city %>, <%= listing.state %> &nbsp; &nbsp;  
					    <%= link_to number_to_phone(listing.contactphone, area_code: true), 			  				phone_number_link(listing.contactphone) %> </b>
						<p><%= raw(listing.shortdescription) %><br>
					<% end %>
					<% else %>
					<p>No listings found! </p>
					<% end %>
				   </div>
			   <div class="col-xs-6 col-sm-5 col-md-5">
				   <p align="right"> </p>
			   </div>
		   </div>
		<div class="container", align="center">
			<%= will_paginate @listings %>
		</div>
	</div>
</div>
</div>
</div>