config/routes.rb
Pilotcar::Application.routes.draw do


  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :bids
  resources :pins

  resources :listings do
    collection do
      get 'search'
    end
    resources :notifications
    resources :pins
  end

  resources :notifications
  resources :pins

  resources :categories do
    resources :subcategories do
      resources :listings
    end
  end

  resources :loads do
    resources :bids
  end

  devise_for :truckers
  devise_for :pilots #, controllers: { registrations: "pilots/registrations", sessions: "pilots/sessions" }

  # Static
  root "pages#home"
  get "testhome" => "pages#home2"
  get "contact" => "pages#contact"
  get "about" => "pages#about"
  get "signup" => "pages#signup"
  get "privacystatement" => "pages#privacy"

  #custom routes
  get "/loads/:id/clone"	=> "loads#clone"
  get "clone" => "loads#clone"
  match '/mylistings', to: 'listings#mylistings', via: :get
  match '/adminlistings', to: 'listings#adminlistings', via: :get
  match '/subcategories/find_by_category', to: 'subcategories#find_by_category', via: :post
  get "/states" => "categories#index"

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

end

app/views/layouts/_footer.html.erb
 <div class="navbar navbar-bottom">
	<div class="container">
	   <p class="navbar-text pull-left" >
		   <i class="fa fa-cog fa-spin fa-1x"></i> PilotCarFinder.com by <br>
		   <a href="http://localreachbranding.com">Local Reach Branding - Reno NV</a><br>
		   9900 Wilbur May Parkway Suite 3901<br>
		   Reno, Nevada 89521<br>
		   
	   </p>
	   <p class="navbar-text pull-right" align="right" >
		  <%= link_to number_to_phone("7755441112", area_code: true), phone_number_link("7755441112") %> <br>
		  <%= link_to "pilotcarfinder@gmail.com", "email: pilotcarfinder@gmail.com" %><br>
		  Copyright (c) 2016<br>
		  <%= link_to "Privacy Statement", privacystatement_path %> - <%= link_to "sitemap.xml", "../sitemap.xml" %><br>
	   </p>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
	<nav class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
	  <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="../">pilotcarfinder.com</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
	  <ul class="nav navbar-nav navbar-right">
		  	  <li><%= link_to "Home", root_path %></li>
		  	  <li><%= link_to "Search", states_path %></li>
	          <li><%= link_to "About", about_path %></li>
	          <% if trucker_signed_in? %>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Trucker's Menu &nbsp;
                  <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
			  		  <li><%= link_to 'New Pilot Car Request (coming soon)', "#" %></li>
					  <li><%= link_to 'Your Requests List (coming soon)', "#" %></li>
			  		  <li><%= link_to "Account Settings", edit_trucker_registration_path %></li>
                  </ul>
              </li>  
	            <li><%= link_to "Log out", destroy_trucker_session_path, method: :delete %></li>
	          <% else %>
	          <% if pilot_signed_in? %>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Pilot's Menu &nbsp;
                  <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
					  <li><%= link_to 'Create New Listing', new_listing_path %></li>
					  <li><%= link_to 'My Listings', mylistings_path %></li>
			  		  <li><%= link_to "Account Settings", edit_pilot_registration_path %></li>
                  </ul>
              </li>  
	            <li><%= link_to "Log out", destroy_trucker_session_path, method: :delete %></li>
	          <% else %>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account Sign In &nbsp;
                  <b class="caret"></b>
                  </a>
			  <ul class="dropdown-menu">
				  <li><%= link_to "Pilot Sign in", new_pilot_session_path %></li>
			  </ul>
			   </li>  
			  <% end %>
			  <% end %>
	      </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.navbar.container -->
</nav>
</nav>

app/views/layouts/_search.html.erb
<div class="container">
	<div class="well well-sm">
		<div class="row">
			<%= form_tag search_listings_path, method: :get do |f| %>
			<div class="form-group">	
				<div class="col-xs-12 col-md-3">
					<div class="form-group">
						<%= text_field_tag :search, nil, class: "form-control", placeholder: 'search (any word)' %>
					</div>
				</div>	
				<div class="col-xs-12 col-md-3">
					<div class="form-group">
						<%= text_field_tag :location, nil, class: "form-control", placeholder: 'near (city or zipcode)' %>
					</div>
				</div>
				<div class="col-xs-6 col-md-6">
					<div class="form-group">
						<%= submit_tag 'SEARCH', class: "btn btn-primary btn-lge" %>
						<%= link_to "Search by State or Metro Area", states_path, class: "btn btn-default btn-lge" %>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div> 
</div>

app/views/layouts/_social.html.erb
<table>
<tr>
<% if @listing.blog.present? %>
<td>
      	<div class="button"> <%= link_to @listing.blog, target: '_blank', :rel => 'nofollow' do %> <i class="fa fa-wordpress fa-2x"></i> &nbsp; <% end %></div>
</td>
<% end %>

<% if @listing.facebook.present? %> 
<td>
		<div class="button"> <%= link_to @listing.facebook, target: '_blank', :rel => 'nofollow' do %> <i class="fa fa-facebook-square fa-2x"></i>  &nbsp; <% end %></div>
</td>
<% end %>	

<% if @listing.twitter.present? %> 
<td>
		<div class="button"> <%= link_to @listing.twitter, target: '_blank', :rel => 'nofollow' do %> <i class="fa fa-twitter-square fa-2x"></i> &nbsp;  <% end %></div>
</td>
<% end %>

<% if @listing.instagram.present? %> 
<td>
		<div class="button"> <%= link_to @listing.instagram, target: '_blank', :rel => 'nofollow' do %> <i class="fa fa-instagram fa-2x"></i> &nbsp;  <% end %></div>
</td>
<% end %>

<% if @listing.pinterest.present? %> 
<td>
		<div class="button"> <%= link_to @listing.pinterest, target: '_blank', :rel => 'nofollow' do %> <i class="fa fa-pinterest-square fa-2x"></i> &nbsp;  <% end %></div>
</td>
<% end %>

<% if @listing.google.present? %> 
<td>
		<div class="button"> <%= link_to @listing.google, target: '_blank', :rel => 'nofollow' do %> <i class="fa fa-google-plus-square fa-2x"></i> &nbsp;  <% end %></div>
</tr>
<% end %>
</table>

app/views/layouts/_tripleboxes.html.erb
<div class="container", align="center">
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
		<i class="fa fa-home fa-taxi fa-5x"></i>
      <div class="caption">
        <h4>LIMITED TIME OFFER</h4>
		<h3>FREE FOREVER<br>Premium Listing</h3>
        <p>
		Website Links!<br>
		Stylized (fancy pants) listing!<br>
		Up to 12 High Resolution Photos!<br>
		Social Media Links!<br>
		Easy Contact Email System!<br>
		No fee EVER!<br>
		(Limited to first 1000 Pilot Car Listings)<br>
		</p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <i class="fa fa-home fa-truck fa-5x"></i>
      <div class="caption">
        <h4>FREE & EASY FOR TRUCKERS</h4>
		<h3>Search, Find, Contact.</h3>
        <p>
		Search by State<br>
		Search by Metro Area<br>
		Search keyword<br>
		All Pilot contact info<br>
		Built for Speed & ease<br>
		Easy Contact Email System!<br>
		No fee EVER!<br><br>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <i class="fa fa-home fa-globe fa-5x"></i>
      <div class="caption">
        <h4>SEARCH THE USA EASIER</h4>
		<h3>Search, Find, Contact.</h3>
        <p>
		Search by State<br>
		Search by Metro Area<br>
		Search keyword<br>
		All Pilot contact info<br>
		Built for Speed & ease<br>
		Easy Contact Email System!<br>
		No fee EVER!<br><br>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<%= display_meta_tags site: 'Pilot Cars & Oversize Load Escorts' %>
  	<%= stylesheet_link_tag "application", media: "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
	<%= favicon_link_tag 'favicon.ico' %>
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="msvalidate.01" content="40A1F818D21ADE4DC5C0D526FBD21AEF" />
</head>
<body data-no-turbolink="true">
<%= render 'layouts/header' %>
	<div class="container">
			<% flash.each do |type, message| %>
				<div class="alert alert-info fade-in">
					<button class="close" data-dismiss="alert">x</button>
					<%= message %>
				</div>
			<% end %>
	</div>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>